name:                aoc2019
version:             0.1.0.0
github:              "githubuser/aoc2019"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2019#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- protolude
- mtl
- containers
- vector
- unordered-containers
- megaparsec
- text
- lens
- transformers
- recursion-schemes
- raw-strings-qq
- prettyprinter
- extra

default-extensions:
- OverloadedStrings
- ExistentialQuantification
- NoMonomorphismRestriction
- FlexibleContexts
- TypeFamilies
- ConstraintKinds
- NamedFieldPuns
- LambdaCase
- MultiWayIf
- TupleSections
- GeneralizedNewtypeDeriving
- TypeApplications
- PatternSynonyms
- ViewPatterns

ghc-options:
- -O2

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - tasty
    - tasty-hspec

benchmarks:
  benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - aoc2019
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
