name:                aoc2021
version:             0.1.0.0
license:             BSD3

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- mtl
- containers
- vector
- unordered-containers
- megaparsec
- text
- optics
- transformers
- recursion-schemes
- raw-strings-qq
- prettyprinter
- extra

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ExistentialQuantification
- NoMonomorphismRestriction
- FlexibleContexts
- TypeFamilies
- ConstraintKinds
- NamedFieldPuns
- LambdaCase
- MultiWayIf
- TupleSections
- GeneralizedNewtypeDeriving
- TypeApplications
- PatternSynonyms
- ViewPatterns

ghc-options:
- -O2

library:
  source-dirs: src

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - tasty
    - tasty-hspec
